[libraries]
configurate = "org.spongepowered:configurate-core:4.2.0"
annotations = "org.jetbrains:annotations:26.0.2"
configurate-helper = "io.github.ynverxe:configurate-helper:1.2.0"
slf4j = "org.slf4j:slf4j-api:2.0.17"
paper-api = "io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT"
cloud-core = "org.incendo:cloud-core:2.0.0"
cloud-annotations = "org.incendo:cloud-annotations:2.0.0"
cloud-paper = "org.incendo:cloud-paper:2.0.0-beta.10"
mock-bukkit = "org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.72.6"
slf4j-api = "org.slf4j:slf4j-api:2.0.17"
adventure-api = "net.kyori:adventure-api:4.24.0"
adventure-minimessage = "net.kyori:adventure-text-minimessage:4.24.0"